languageCode = "en-us"
title = "Olli Saarikivi"
publishdir = "site"
baseurl = "http://olli.saarikivi.fi/"
canonifyurls = true
[author]
    name = "Olli Saarikivi"
[params]
	Description = ""
	disqusShortname = "ollisaarikivi"
[Taxonomies]
	collection = "collections"
[permalinks]
	post = "/:year/:month/:slug/"
[[menu.main]]
    name = "About"
    Url = "/"
    weight = 0
[[menu.main]]
    name = "Posts"
    Url = "/collections/posts"
    weight = 100