languageCode = "en-us"
title = "Olli Saarikivi"
publishdir = "site"
baseurl = "http://ulber.iki.fi/"
disqusShortname = "ollisaarikivi"
canonifyurls = true
[author]
    name = "Olli Saarikivi"
[params]
	Description = ""
[Taxonomies]
	collection = "collections"
[permalinks]
	post = "/:year/:month/:slug/"
[[menu.main]]
    name = "Posts"
    Url = "/collections/posts"
    weight = 100